apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-http-config
  namespace: myapp-prod
data:
  config: |
    http {
      server {
        location / {
        root /data/html;
        }

        location /images/ {
          root /data;
        }
      }
    }

---------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: myapp-api-key
type: Opaque
data:
  myapikey: YMRtd5thSaW4=

----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: myapp-prod
spec:
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config
        - mountPath: /usr/var/nginx/html/keys
          name: api-key
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-http-config
            items:
            - key: config
              path: nginx.conf
        - name: api-key
          secret:
            name: myapp-api-key
            secretname: myapikey

